Stick to ubuntu-22.04 for now for frontend-ci.yml
Two days back GitHub jumped over to 24.04 for -latest and now this workflow fails with

	Package libicu70 is not available, but is referred to by another package.
	This may mean that the package is missing, has been obsoleted, or
	is only available from another source

	Package libasound2 is a virtual package provided by:
	  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
	  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)

	E: Package 'libasound2' has no installation candidate
	E: Package 'libicu70' has no installation candidate
	E: Unable to locate package libffi7
	E: Unable to locate package libx264-163
	Failed to install browsers
	Error: Installation process exited with code: 100

I think it might get resolved later by "itself" upstream but for now it
provides the easiest way to bring back CI into green zone.